[book]
authors = ["Ashish Patel"]
language = "en"
multilingual = false
src = ""
title = "wiki"

[build]
build-dir = "book"

[preprocessor.autosummary]
index-name = "index.md"


[output.html.fold]
enable = true
level = 0


[output.html]
additional-js = ["./theme/custom.js","./theme/mermaid.min.js", "./theme/mermaid-init.js"]
mathjax-support = true
default-theme = "latte"
preferred-dark-theme = "latte"
additional-css = ["./theme/catppuccin.css","./theme/ashish.css"]
no-section-label = true
git-repository-url = "https://github.com/ashishdotme/notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ashishdotme/notes/edit/master{path}"
site-url = "https://wiki.ashish.me"

[preprocessor.mermaid]
command = "mdbook-mermaid"