name: Build notes.ashish.me

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        # We need full history to introspect created/updated:
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build database
        run: python build_database.py
      - name: Update README
        run: |-
          python build_readme.py --rewrite
          cat README.md
      - name: Commit and push if README changed
        run: |-
          git diff
          git config --global user.email "ashishsushilpatel@gmail.com"
          git config --global user.name "Ashish Patel"
          git diff --quiet || (git add . && git commit -m "chore: update README")
          git push
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
          # mdbook-version: 'latest'
      - uses: brndnmtthws/rust-action-cargo-binstall@v1
        with:
          packages: mdbook-mermaid mdbook-autosummary
      - run: mdbook build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: cd78c815cc8afdc708dedabdcb7ade24
          projectName: wiki
          directory: book
          branch: master
      - name: Deploy Datasette using Vercel
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: |-
          datasette publish vercel notes.db \
            --token $NOW_TOKEN \
            --branch 0.64.x \
            --project ashish-notes \
            --metadata .github/metadata.yaml \
            --static static:static \
            --install datasette-template-sql \
            --install "datasette-atom>=0.7" \
            --install datasette-json-html \
            --install beautifulsoup4 \
            --install datasette-debug-asgi \
            --install "datasette-graphql>=0.12" \
            --install datasette-media \
            --plugins-dir .github/plugins \
            --template-dir .github/templates \
            --public
